config/routes.rb
Freemint::Application.routes.draw do

  match 'vat' => 'company_events#index'
  get "/company_events" => redirect("/vat")
  
  resources :company_events

  resources :expenses

  get "home/index"
  root :to => 'home#index'

  post "home/signup"
  post "home/login"
  get "home/logout"

  get "welcome/index"

  resources :invoices
  get 'invoices/:id/pdf' => 'invoices#pdf'

  match 'company' => 'companies#index'
  post 'company/modify' => 'companies#modify'
  put  'company/modify' => 'companies#modify'

end

app/models/company_event.rb
class CompanyEvent < ActiveRecord::Base
  attr_accessible :date, :event_id, :flat_rate_1, :flat_rate_2, :new_flat_rate

  belongs_to :company
  belongs_to :event

  validates :company_id,
  					:date,
  					:event_id,
  					:presence => true

  validates :new_flat_rate, 
  					:flat_rate_1, 
  					:flat_rate_2,
  					:numericality => { :greater_than_or_equal_to => 0 }

  validates :date, :format => { :with => /^(\d{4}-(0[1-9]|1[012])-(01))$/,
            :message => "is not valid"}


  def self.get_events(company_id)
    self.includes(:event).where(:company_id => company_id).order("date DESC").group_by { |ce| ce.date.strftime("%Y") }
  end

end

app/controllers/company_events_controller.rb
class CompanyEventsController < ApplicationController

  def index
    company_id = Company.where(:user_id => session[:user_id]).first.id
    @company_events = CompanyEvent.get_events(company_id) 

  	@company_event = CompanyEvent.new
    @company_event.date = Date.today

    @current_year = CompanyEvent.last == nil ? Date.today.year : CompanyEvent.last.created_at.year
  end

  def create
  	@company_event = CompanyEvent.new(params[:company_event])
  	@company_event.company_id = Company.where(:user_id => session[:user_id]).first.id
    @company_event.date = "01-" + params[:company_event][:date]

    respond_to do |format|
      if @company_event.save
        format.html { redirect_to company_events_url }
        format.js 
      else
        format.html { render :action => "index" }
      end
    end
  end

  def edit
    company_id = Company.where(:user_id => session[:user_id]).first.id
    @company_event = CompanyEvent.find_by_id_and_company_id(params[:id], company_id) || not_found

    respond_to do |format|
      format.js
    end
  end

  def update
    company_id = Company.where(:user_id => session[:user_id]).first.id
    @company_event = CompanyEvent.find_by_id_and_company_id(params[:id], company_id) || not_found

    @company_event.assign_attributes params[:company_event]
    @company_event.date = "01-" + params[:company_event][:date]
    
    respond_to do |format|
      if @company_event.save
        format.html { redirect_to company_events_url }
        format.js
      else
        format.html { render :action => 'index' }
      end
    end
  end

  def destroy
    company_id = Company.where(:user_id => session[:user_id]).first.id
    @company_event = CompanyEvent.find_by_id_and_company_id(params[:id], company_id) || not_found
    @company_event.destroy()

    respond_to do |format|
      format.html { redirect_to company_events_url }
      format.js
    end
  end

end

app/helpers/company_events_helper.rb
module CompanyEventsHelper
end

app/views/company_events/_form.html.erb
<%= form_for(@company_event, :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

	<div id="error_explanation_company_event" class="alert alert-error">
		<strong></strong>
		<ul></ul>
	</div>

	<div class="row-fluid">
		<div class="control-group">
			<%= f.label :date, 'Date', :class => 'control-label' %>
			<div class="controls">
				<%= f.text_field :date, :class => 'input-small required', :placeholder => 'Date',
				:value => (@company_event.date.strftime('%m-%Y') unless @company_event.date.nil?) %> 
			</div>
		</div>
	</div>

	<div class="row-fluid">
		<div class="control-group">
			<%= f.label :event_id, 'Event', :class => 'control-label' %>
			<div class="controls">
				<%= f.select :event_id, options_from_collection_for_select(Event.all, :id, :name, @company_event.event_id), 
						{:include_blank => "Choose an event"}, { :class => "input-xlarge"} %>
			</div>
		</div>
	</div>

	<div class="row-fluid" id="new_flat_rate">
		<div class="control-group input-append">
			<%= f.label :new_flat_rate, 'New Flat Rate', :class => 'control-label' %>
			<div class="controls">
				<%= f.text_field :new_flat_rate, :class => 'input-mini', :placeholder => 'New Flat Rate', 
						:value => number_with_precision(@company_event.new_flat_rate,
							:precision => 2, :strip_insignificant_zeros => true) %>
				<span class="add-on required">%</span>
			</div>
		</div>
	</div>

	<div class="row-fluid" id="flat_rate_1">
		<div class="control-group input-append">
			<%= f.label :flat_rate_1, 'First Year', :class => 'control-label' %>
			<div class="controls">
				<%= f.text_field :flat_rate_1, :class => 'input-mini', :placeholder => 'First Year', 
						:value => number_with_precision(@company_event.flat_rate_1,
							:precision => 2, :strip_insignificant_zeros => true) %>
				<span class="add-on required">%</span>
			</div>
		</div>
	</div>

	<div class="row-fluid" id="flat_rate_2">
		<div class="control-group input-append">
			<%= f.label :flat_rate_2, 'After First Year', :class => 'control-label' %>
			<div class="controls">
				<%= f.text_field :flat_rate_2, :class => 'input-mini', :placeholder => 'After First Year', 
						:value => number_with_precision(@company_event.flat_rate_2,
							:precision => 2, :strip_insignificant_zeros => true) %>
				<span class="add-on required">%</span>
			</div>
		</div>
	</div>
<% end %>

app/views/company_events/create.js.erb
$("#new_company_event")[0].reset();
$("#newModal").modal('hide');

setTimeout(function(){
  $("#company_events").load('/vat #company_events');
}, 1000);

app/views/company_events/destroy.js.erb
setTimeout(function(){
  $("#company_events").load('/vat #company_events');
}, 1000);

$("#editModal").modal('hide');
$("#destroyModal").modal('hide');

app/views/company_events/edit.js.erb
$("#editModal").modal('show');

$("#editModal .modal-body").html("<%= j render :partial => 'form' %>");

$("#destroyCompanyEvent").replaceWith("<%= j link_to 'Delete', @company_event, :id => 'destroyCompanyEvent', :class => 'btn btn-action', :remote => true, :method => :delete %>");

var editModal = "#editModal ";
var new_flat_rate = "#new_flat_rate";
var flat_rate_1 = "#flat_rate_1";
var flat_rate_2 = "#flat_rate_2";

$(editModal + "#company_event_date").datepicker({
  format: "mm-yyyy",
  viewMode: "months",
  minViewMode: "months"
});

$(editModal + "#company_event_event_id").change(function(){
  // reset_optional_fields
  $(editModal + "#company_event_new_flat_rate").val(0);
  $(editModal + "#company_event_flat_rate_1").val(0);
  $(editModal + "#company_event_flat_rate_2").val(0);

  $('.input_error').removeClass('input_error');
  $(editModal + "#error_explanation_company_event").hide();

  var value_select = $(this).val();

  switch (value_select)
  {
    case '2':
      $(editModal + flat_rate_1).show();
      $(editModal + flat_rate_2).show();
      break;
    case '4':
      $(editModal + new_flat_rate).show();
      break;
    default:
      // hide_optional_fields
      $(editModal + new_flat_rate).hide();
      $(editModal + flat_rate_1).hide();
      $(editModal + flat_rate_2).hide();
  }
});

var event_id = <%= @company_event.event_id %>;
if(event_id === 2)
{
  $(editModal + flat_rate_1).show();
  $(editModal + flat_rate_2).show();
}
else if(event_id === 4)
{
  $(editModal + new_flat_rate).show();
}

app/views/company_events/index.html.erb
<% content_for :header do %>
	<%= stylesheet_link_tag 'application-company-events', :media => 'all' %>
	<%= stylesheet_link_tag "timeline", :media => "all" %>
	<%= javascript_include_tag "company_events" %>
	<script type="text/javascript">$(document).ready(function() { CompanyEventPage.start(); });	
	</script>
<% end %>

<%= link_to 'Add New Event', '#', :id => "add_event", :class => "btn btn-info" %>

<% if @company_event.errors.any? %>
	<div id="error_explanation" class="alert alert-error">
		<strong>Company Event saving failed because of <%= pluralize(@company_event.errors.count, "error") %>:</strong>
		<ul>
			<% @company_event.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<section id="company-event">
	<div id="newModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
			<h3 id="myModalLabel">New Event</h3>
		</div>
		<div class="modal-body">
			<%= render :partial => 'form' %>
		</div>
		<div class="modal-footer">
			<button id="submitCompanyEvent" type="submit" class="btn btn-action">Create</button>
			<small>
				<em>or</em>
				<a href='#' data-dismiss="modal" aria-hidden="true">cancel</a>
			</small>
		</div>
	</div>

	<div id="editModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
			<h3>Edit Event</h3>
		</div>
		<div class="modal-body">
			<%= render :partial => 'form' %>
		</div>
		<div class="modal-footer">
			<%= link_to 'Delete', '#', :class => 'btn btn-danger pull-left', :data => { :toggle => 'modal', :target => '#destroyModal' } %>
			<button id="editCompanyEvent" type="submit" class="btn btn-action">Update</button>
			<small>
				<em>or</em>
				<a href='#' data-dismiss="modal" aria-hidden="true">cancel</a>
			</small>
		</div>
	</div>

	<div id="destroyModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-body">
			Are you sure you want to delete this event?
		</div>
		<div class="modal-footer">
			<button id="destroyCompanyEvent" type="submit" class="btn btn-action">Delete</button>
			<small>
				<em>or</em>
				<a href='#' id="close_destroy_modal" data-dismiss="modal" aria-hidden="true">cancel</a>
			</small>
		</div>
	</div>
</section>

<div id="company_events" class="timeline-border">
	<div class="line"></div>
	<% @company_events.each do |year, ces| %>
		<div class="year"><span><%= year %></span></div>
		<% ces.each do |ce| %>
			<span id="<%= ce.id %>" class="month"><%= ce.date.strftime("%B") %></span><span></span>
			<%= link_to ce.event.name, edit_company_event_path(ce), :id => ce.id, :class => "event", :remote => true %>
		<% end %>
	<% end %>
</div>

app/views/company_events/update.js.erb
$("#editModal").modal('hide');

setTimeout(function(){
  $("#company_events").load('/vat #company_events');
}, 1000);

<% @company_event = CompanyEvent.new %>
$("#editModal .modal-body").html("<%= j render :partial => 'form' %>");
$("#new_company_event")[0].reset();