config/routes.rb
Freemint::Application.routes.draw do

  match 'vat' => 'company_events#index'
  get "/company_events" => redirect("/vat")
  
  resources :company_events

  resources :expenses

  get "home/index"
  root :to => 'home#index'

  post "home/signup"
  post "home/login"
  get "home/logout"

  get "welcome/index"

  resources :invoices
  get 'invoices/:id/pdf' => 'invoices#pdf'

  match 'company' => 'companies#index'
  post 'company/modify' => 'companies#modify'
  put  'company/modify' => 'companies#modify'

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base

  attr_accessible :number,
                  :date,
                  :vat_rate,

                  :client_name,
                  :client_company_no,
                  :client_address_1,
                  :client_address_2,
                  :client_town,
                  :client_postcode,
                  :client_county,
                  :client_vat_code,

                  :self_name,
                  :self_address_1,
                  :self_address_2,
                  :self_town,
                  :self_postcode,
                  :self_county,

                  :due_date,
                  :self_bank,
                  :self_account,
                  :self_sort_code,

                  :inv_total,
                  :inv_vat_total,
                  :inv_grand_total,

                  :print_payment_details

  belongs_to :user
  has_many :invoice_rows, :autosave => true

  validates :number, :presence => true
  validates :date, :presence => true
  validates :vat_rate, :presence => true, :numericality => { :greater_than_or_equal_to => 0, :less_than => 100 }
  validates :client_name, :presence => true
  validates :self_name, :presence => true
  validates :invoice_rows, :length => {:minimum => 1}
  validates :user, :presence => true

  validates :inv_total, :presence => true, :numericality => { :greater_than_or_equal_to => 0 }
  validates :inv_vat_total, :presence => true, :numericality => { :greater_than_or_equal_to => 0 }
  validates :inv_grand_total, :presence => true, :numericality => { :greater_than_or_equal_to => 0 }

  validates_inclusion_of :print_payment_details, :in => [true, false]

  def calculate_totals
    calculate_inv_total
    calculate_vat_total
    calculate_inv_grand_total
  end

  def update_client_data(client)
    self.client_name = client.name
    self.client_vat_code = client.vat_code
    self.client_address_1 = client.address_1
    self.client_address_2 = client.address_2
    self.client_town = client.town
    self.client_postcode = client.postcode
    self.client_county = client.county
  end

  def self.next_number(current_user_id)
    last_number = Invoice.maximum('0+number', :conditions => ["user_id = #{current_user_id}"])
    (last_number.to_i + 1).to_s unless last_number == 0
  end

  private
  def calculate_inv_total
    self.inv_total = 0.0
    invoice_rows.each do |row|
      self.inv_total += row.net_price.to_f
    end
  end

  def calculate_vat_total
    unless self.vat_rate.nil?
      self.inv_vat_total = self.vat_rate.to_d / 100 * self.inv_total
    end
  end

  def calculate_inv_grand_total
    self.inv_grand_total = self.inv_vat_total + self.inv_total
  end

  end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def index
    @invoices = Invoice.order('date DESC').find_all_by_user_id(current_user.id)
  end

  def new
    @invoice = Invoice.new

    company = Company.find_by_user_id(current_user.id)
    if company
      @invoice.self_name = company.name
      @invoice.self_address_1 = company.address_1
      @invoice.self_address_2 = company.address_2
      @invoice.self_town = company.town
      @invoice.self_postcode = company.postcode
      @invoice.self_county = company.county
    end
    @invoice.number = Invoice.next_number current_user.id
    @invoice.date = Time.now.strftime('%d/%m/%Y')
    @invoice.print_payment_details = true

    find_or_create_client_by_invoice_client_data @invoice
    create_clients_json
  end

  def create
    @invoice = Invoice.new(params[:invoice])
    @invoice.invoice_rows = []
    add_new_rows params[:new_invoice_rows]

    @invoice.user_id = session[:user_id]
    @invoice.calculate_totals

    update_company_details
    create_or_update_client_and_invoice_client_data

    if @invoice.save
      redirect_to :action => :index, notice: 'Invoice was successfully created.'
    else
      render :action => :new
    end
  end

  def edit
    @invoice = Invoice.find_by_id_and_user_id(params[:id], current_user.id) || not_found

    find_or_create_client_by_invoice_client_data @invoice
    create_clients_json
  end

  def update
    @invoice = Invoice.find_by_id_and_user_id(params[:id], current_user.id) || not_found

    @invoice.assign_attributes params[:invoice]
    update_rows params[:invoice_rows]
    add_new_rows params[:new_invoice_rows]
    @invoice.calculate_totals

    update_company_details
    create_or_update_client_and_invoice_client_data

    if @invoice.save
      redirect_to :action => :index
    else
      render :action => :edit
    end
  end

  def pdf
    @invoice = Invoice.find_by_id_and_user_id(params[:id], current_user.id) || not_found
    pdf = InvoicePdfGenerator.new(@invoice)
    send_data pdf.render_pdf, {
        :filename => "invoice_#{@invoice.number}.pdf",
        :type => 'application/pdf',
        :disposition => 'attachment'
    }
  end

  def self.clients_json(clients)
    clients_json = []
    clients.each do |c|
      clients_json << {
          :value => c.id,
          :label => c.name,
          :vat_code => c.vat_code,
          :address_1 => c.address_1,
          :address_2 => c.address_2,
          :town => c.town,
          :postcode => c.postcode,
          :county => c.county
      }
    end

    clients_json = clients_json.to_json
  end

  private
  def add_new_rows(new_invoice_rows)
    new_invoice_rows.each do |row|
      @invoice.invoice_rows.build(row).calculate_net_price
    end unless new_invoice_rows.nil?
  end

  def update_rows(invoice_rows)
    invoice_rows ||= {}
    @invoice.invoice_rows.each do |row|
      updated_row = invoice_rows[row.id.to_s]
      if updated_row.nil?
        row.delete
      else
        row.assign_attributes updated_row
        row.calculate_net_price
      end
    end
  end

  def create_or_update_client_and_invoice_client_data
    client_id = params[:client_id]
    @client = Client.find_by_id_and_user_id(client_id, current_user.id)
    if @client
      @client.assign_attributes params[:client]
    else
      @client = Client.new(params[:client])
      @client.user_id = current_user.id
    end

    create_clients_json

    if @client.save
      @invoice.update_client_data @client
    end
  end

  def update_company_details
    new_company_attributes = {:name => params[:invoice][:self_name], :address_1 => params[:invoice][:self_address_1], :address_2 => params[:invoice][:self_address_2], :town => params[:invoice][:self_town], :postcode => params[:invoice][:self_postcode]}
    company = Company.find_by_user_id(current_user.id)
    if company
      company.assign_attributes(new_company_attributes)
    else
      company = Company.new(new_company_attributes)
      company.user_id = current_user.id
    end
    company.save!
  end

  def create_clients_json
    clients = Client.find_all_by_user_id(current_user.id)
    @clients_json = InvoicesController.clients_json(clients)
  end

  def find_or_create_client_by_invoice_client_data(invoice)
    clients = Client.find_all_by_user_id(current_user.id)
    @client = clients.detect{|c| c.name == invoice.client_name}

    if not @client
      @client = Client.new
      @client.update_from_invoice invoice
    end
  end

end

app/views/invoices/_form.html.erb
<script>
    $(document).ready(function() {
        InvoiceClientsAutocomplete.start().installAutocompleteListeners(<%= @clients_json.html_safe %>);
    });

</script>

<%= form_for(@invoice, :html => { :class => 'form-horizontal' }) do |f| %>
  <% if @invoice.errors.any? || @client.errors.any? %>
    <div id="error_explanation" class="alert alert-error">
      <strong>Invoice saving failed because of <%= pluralize(@invoice.errors.count, "error") %>:</strong>
      <ul>
        <% @invoice.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        <% @client.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="perforated">
    <section id="invoice">
      <section id="invoice-details">
        <h1 id="invoice-title-heading">
          Invoice
        </h1>
        <hr/>
        <div class="control-group">
          <%= f.label :number, 'Number & date', :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :number, :class => 'input-mini required', :placeholder => 'Number' %>
            <%= f.text_field :date, :class => 'datepicker input-small required', :placeholder => 'Date',
              :value => (@invoice.date.strftime('%d/%m/%Y') unless @invoice.date.nil?) %>
          </div>
        </div>
        <div class="control-group input-append">
          <%= f.label :vat_rate, 'VAT rate', :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :vat_rate, :class => 'input-mini', :placeholder => 'VAT',
                             :value => number_with_precision(@invoice.vat_rate, :precision => 2, :strip_insignificant_zeros => true) %>
            <span class="add-on required">%</span>
          </div>
          <span class="help-block">VAT rate is always 0% unless you're VAT registered with HMRC.</span>
        </div>
        <div class="control-group input-append">
          <%= f.label :client_name, 'Your client', :class => 'control-label' %>
          <div class="controls">
            <%= text_field :client, :name, :id => 'client_name_invoice_page',:class => 'required', :placeholder => 'Client company name' %>
            <span class="add-on required">
              <a href="#client-modal" role="button" data-toggle="modal">more</a>
            </span>
          </div>
          <span class="help-block">Start typing to search for clients.</span>
        </div>
        <div class="control-group">
          <label class="control-label">You</label>
          <div class="controls mid-align">
            <a id="check-details-link" href="#self-modal" style="display: none" role="button" data-toggle="modal">Check your details</a>
            <a id="no-details-link" href="#self-modal" style="display: none" role="button" data-toggle="modal" class="label label-important">We're missing your company details. Click here to enter them.</a>
          </div>
        </div>

        <div class="control-group input-append">
          <%= f.label :print_payment_details, 'Payment details on invoice', :class => 'control-label' %>
          <div class="controls">
            <%= f.check_box :print_payment_details, :class => 'checkbox' %>
          </div>
        </div>
      </section>

      <div id="client-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">Your client</h3>
        </div>
        <div class="modal-body invoice-client">
          <div class="control-group">
            <%= f.label :client_name, 'Client name', :class => 'control-label' %>
            <div class="controls">
              <%= text_field :client, :name, :class => 'required', :placeholder => 'Client company name' %>
              <%= hidden_field :client, :id, :name => 'client_id' %>
            </div>
            <span class="help-block">Start typing to search for clients.</span>
          </div>
          <div class="control-group">
            <%= f.label :client_vat_code, 'VAT code (opt)', :class => 'control-label' %>
            <div class="controls">
              <%= text_field :client, :vat_code, :placeholder => 'Company VAT code' %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :client_address_1, 'Street', :class => 'control-label' %>
            <div class="controls">
              <%= text_field :client, :address_1, :placeholder => 'Street address' %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :client_address_2, 'Street 2 (opt)', :class => 'control-label' %>
            <div class="controls">
              <%= text_field :client, :address_2, :placeholder => 'Address continued' %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :client_town, 'Town', :class => 'control-label' %>
            <div class="controls">
              <%= text_field :client, :town, :placeholder => 'Town' %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :client_postcode, 'Postcode', :class => 'control-label' %>
            <div class="controls">
              <%= text_field :client, :postcode, :class => 'input-small', :placeholder => 'Postcode' %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        </div>
      </div>

      <div id="self-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="self-invoice-modal-label" aria-hidden="true">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="self-invoice-modal-label">About you</h3>
        </div>
        <div class="modal-body self-client">
          <div id="invoice-self">
            <div class="control-group">
              <%= f.label :client_vat_code, 'Company name', :class => 'control-label' %>
              <div class="controls">
                <%= f.text_field :self_name, :class => 'required', :placeholder => 'Your company name' %>
              </div>
              <span class="help-block">Set automatically from company details.</span>
            </div>
            <div class="control-group">
              <%= f.label :self_address_1, 'Street', :class => 'control-label' %>
              <div class="controls">
                <%= f.text_field :self_address_1, :placeholder => 'Street address' %>
              </div>
            </div>
            <div class="control-group">
              <%= f.label :self_address_2, 'Street 2 (opt)', :class => 'control-label' %>
              <div class="controls">
                <%= f.text_field :self_address_2, :placeholder => 'Address continued' %>
              </div>
            </div>
            <div class="control-group">
              <%= f.label :self_town, 'Town', :class => 'control-label' %>
              <div class="controls">
                <%= f.text_field :self_town, :placeholder => 'Town' %>
              </div>
            </div>
            <div class="control-group">
              <%= f.label :self_postcode, 'Postcode', :class => 'control-label' %>
              <div class="controls">
                <%= f.text_field :self_postcode, :class => 'input-small', :placeholder => 'Postcode' %>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        </div>
      </div>

      <hr/>

      <section id="invoice-rows">
        <table class="table table-hover">
          <thead>
          <tr>
            <td>#</td>
            <td>Name</td>
            <td class="numeric">Quantity</td>
            <td class="numeric">Unit (opt)</td>
            <td class="numeric">Unit price</td>
            <td>Total price</td>
          </tr>
          </thead>
          <tbody>
          <tr id="new-invoice-row" class="new-invoice-row invoice-row" style="display: none">
            <td>
              <span class="table-label">Row </span>
              <span class="row-num mid-align"></span>
            </td>
            <td>
              <input type="text" disabled="disabled" name="new_invoice_rows[][name]" placeholder="Type in product/service"
                     class="rw-input required row-name"
                     data-toggle="tooltip" data-placement="top" data-original-title="The name of the product or service being provided to your client (e.g. Consultancy)." />
            </td>
            <td class="numeric">
              <input type="text" disabled="disabled" name="new_invoice_rows[][quantity]" class="rw-input input-mini required numeric row-quantity" placeholder="Qty"
                     data-toggle="tooltip" data-placement="top" data-original-title="The quantity in which the product or service is being provided (e.g. 37.5)." />
            </td>
            <td class="numeric">
              <input type="text" disabled="disabled" name="new_invoice_rows[][unit]" class="rw-input input-mini row-unit numeric" placeholder="Unit"
                     data-toggle="tooltip" data-placement="top" data-original-title="The unit in which the quantity is measured (e.g. hrs)." />
            </td>
            <td class="numeric">
              <input type="text" disabled="disabled" name="new_invoice_rows[][unit_price]" class="rw-input input-mini required numeric row-unit-price" placeholder="£££"
                     data-toggle="tooltip" data-placement="top" data-original-title="The price for when the quantity is 1 (e.g. 39.99)." />
            </td>
            <td>
              <div class="row-net-price mid-align"><%= number_to_currency(0, :unit => '&pound;') %></div>
              <button class="btn btn-danger delete-row" type="button" title="Remove this row from the invoice."
                      data-toggle="tooltip" data-placement="right" data-original-title="Remove this row from the invoice.">-</button>
            </td>
          </tr>
          <% @invoice.invoice_rows.each_with_index do |invoice_row, i| %>
            <%= fields_for 'invoice_rows[]', invoice_row do |rf| %>
              <tr id="invoice-row-<%= i+1 %>" class="invoice-row" data-row="<%= i+1 %>">
                <td>
                  <span class="table-label">Row </span>
                  <span class="row-num mid-align"><%= i+1 %></span>
                </td>
                <td>
                  <%= rf.text_field :name, :class => 'rw-input required row-name', :placeholder => 'Type in product/Service name' %>
                </td>
                <td class="numeric">
                  <%= rf.text_field :quantity, :class => 'rw-input input-mini required numeric row-quantity', :placeholder => 'Qty',
                                    :value => number_with_precision(invoice_row.quantity, :precision => 2, :strip_insignificant_zeros => true) %>
                </td>
                <td class="numeric">
                  <%= rf.text_field :unit, :class => 'rw-input input-mini row-unit numeric', :placeholder => 'Unit' %>
                </td>
                <td class="numeric">
                  <%= rf.text_field :unit_price, :class => 'rw-input input-mini required numeric row-unit-price', :placeholder => '£££',
                                    :value => number_with_precision(invoice_row.unit_price, :precision => 2, :strip_insignificant_zeros => true) %>
                </td>
                <td>
                  <div class="row-net-price mid-align"><%= number_to_currency(invoice_row.net_price || 0, :unit => '&pound;') %></div>
                  <button class="btn btn-danger delete-row" type="button" title="Remove this row from the invoice."
                          data-toggle="tooltip" data-placement="right" data-original-title="Remove this row from the invoice.">-</button>
                </td>
              </tr>
            <% end %>
          <% end %>
          </tbody>
        </table>
      </section>

      <section id="invoice-row-add-box" class="bottom">
        <button id="add-invoice-row-button" class="btn btn-info" type="button" title="Add another product/service to the invoice."
                data-toggle="tooltip" data-placement="bottom" data-original-title="Add another product/service to the invoice.">
          Add invoice row
        </button>
      </section>

      <section id="invoice-totals-box" class="bottom">
        <table id="totals-table">
          <tr>
            <td>Total VAT @ <span id="invoice-total-vat-rate"><%= @invoice.vat_rate %></span>%</td>
            <td>
              <div id="invoice-vat-total" class="numeric"><%= number_to_currency(@invoice.inv_vat_total || 0, :unit => '&pound;') %></div>
            </td>
          </tr>
          <tr>
            <td>Invoice total</td>
            <td>
              <div id="invoice-grand-total" class="numeric"><%= number_to_currency(@invoice.inv_grand_total || 0, :unit => '&pound;') %></div>
            </td>
          </tr>
        </table>
      </section>

      <section id="invoice-actions">
        <%= f.button('Create', :class => 'btn btn-action', :type => 'submit') if @invoice.new_record? %>
        <%= f.button('Update', :class => 'btn btn-action', :type => 'submit') unless @invoice.new_record? %>
        <small>
          <em>or</em>
          <%= link_to 'cancel', { :action => :index } %>
        </small>
      </section>
    </section>


    </section>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<% content_for :header do %>
  <%= stylesheet_link_tag 'application-invoices', :media => 'all' %>
  <%= javascript_include_tag "invoices" %>
  <script type="text/javascript">$(document).ready(function() {InvoicePage.start();});</script>
<% end %>

<%= render 'form' %>

app/views/invoices/index.html.erb
<% content_for :header do %>
  <%= stylesheet_link_tag 'application-invoices', :media => 'all' %>
  <%= javascript_include_tag "invoices" %>
<% end %>

<section id="invoices">

  <div class="invoice invoice-stack new-invoice">
    <%= link_to :action => :new do %>
      <p id="add">+</p>
      <p>Create an invoice</p>
    <% end %>
  </div>

  <% @invoices.each do |invoice| %>
    <div class="invoice">
      <div id="invoice-print">
        <%= link_to '', { :action => :pdf, :id => invoice }, :class=>"active-tooltip", :'data-toggle' => 'tooltip', :title => 'Print this invoice.' %>
      </div>
      <%= link_to edit_invoice_path(invoice) do %>
        <div class="invoice-number">
          <label>Invoice </label># <%= invoice.number %>
        </div>
        <div class="invoice-date">
          <%= invoice.date.strftime('%d/%m/%Y') if invoice.date %>
        </div>
        <div class="invoice-client">
          <%= invoice.client_name %>
        </div>
        <div class="invoice-total">
          <label>Total:</label>
          <span>
            <%= number_to_currency(invoice.inv_grand_total, :unit => "&pound;", :separator => ",", :delimiter => ".") %>
          </span>
        </div>
      <% end %>
    </div>
  <% end %>

</section>

app/views/invoices/new.html.erb
<% content_for :header do %>
  <%= stylesheet_link_tag 'application-invoices', :media => 'all' %>
  <%= javascript_include_tag "invoices" %>
  <script type="text/javascript">$(document).ready(function() {InvoicePage.start();});</script>
<% end %>

<%= render 'form' %>