config/routes.rb
Freemint::Application.routes.draw do

  match 'vat' => 'company_events#index'
  get "/company_events" => redirect("/vat")
  
  resources :company_events

  resources :expenses

  get "home/index"
  root :to => 'home#index'

  post "home/signup"
  post "home/login"
  get "home/logout"

  get "welcome/index"

  resources :invoices
  get 'invoices/:id/pdf' => 'invoices#pdf'

  match 'company' => 'companies#index'
  post 'company/modify' => 'companies#modify'
  put  'company/modify' => 'companies#modify'

end

app/models/company.rb
class Company < ActiveRecord::Base

  attr_accessible :name,
                  :vat_code,
                  :address_1,
                  :address_2,
                  :town,
                  :postcode,
                  :county,
                  :bank,
                  :account,
                  :sort_code

  belongs_to :user

  has_many :company_events
  has_many :events, :through => :company_events

  validates :name, :presence => true
  validates :user, :presence => true

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @company = Company.find_by_user_id(current_user.id) || Company.new
  end

  def modify
    @company = Company.find_by_user_id(current_user.id)

    if @company.nil? ? create(params) : update(params)
      redirect_to :action => :index, notice: 'Company was successfully updated.'
    else
      render :action => :index
    end
  end

  private
  def create(params)
    @company = Company.new(params[:company])
    @company.user_id = current_user.id
    @company.save
  end

  def update(params)
    @company.update_attributes(params[:company])
  end
end

app/views/companies/index.html.erb
<% content_for :header do %>
  <%= stylesheet_link_tag 'application-company', :media => 'all' %>
  <%= javascript_include_tag "company" %>
  <script type="text/javascript">$(document).ready(function() {CompanyPage.start();});</script>
<% end %>

<%= form_for(@company, :url => 'company/modify', :html => { :class => 'form-horizontal' }) do |f| %>
  <% if @company.errors.any? %>
    <div id="error-explanation" class="alert alert-error">
      <strong>Company saving failed because of <%= pluralize(@company.errors.count, "error") %>:</strong>
      <ul>
        <% @company.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% unless params[:notice].nil? %>
    <div id="success-explanation" class="alert alert-success">
      <strong><%= params[:notice] %></strong>
    </div>
  <% end %>


  <div class="perforated">
    <section id="company">
      <section>
        <h1 id="company-title-heading">
          Company details
        </h1>
        <hr/>
        <div class="control-group">
          <%= f.label :name, 'Your business name', :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :name, :class => 'required', :placeholder => 'Your company name' %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :vat_code, 'VAT code', :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :vat_code, :placeholder => 'VAT code' %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :address_1, 'Address', :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :address_1, :class => 'required', :placeholder => 'Street address' %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :address_2, 'Address (cont)', :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :address_2, :placeholder => 'Address continued' %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :town, 'Town', :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :town, :class => 'required', :placeholder => 'Town' %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :postcode, 'Postcode', :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :postcode, :class => 'input-small required', :placeholder => 'Postcode' %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :county, 'County', :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :county, :class => 'required', :placeholder => 'County' %>
          </div>
        </div>
        <hr/>
        <div class="control-group">
          <%= f.label :bank, 'Bank', :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :bank, :placeholder => 'Bank' %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :account, 'Account', :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :account, :placeholder => 'Account' %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :sort_code, 'Sort code', :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :sort_code, :placeholder => 'Sort code' %>
          </div>
        </div>
        <hr/>
        <div class="control-group">
          <label for="vat_timeline" class="control-label">VAT</label>
          <div class="controls">
            <%= link_to 'Manage VAT details', vat_path, :id => 'vat_timeline' %>
          </div>
        </div>
        <hr>
        <div id="company-actions">
          <%= f.button('Update', :class => 'btn btn-action', :type => 'submit') %>
          <small>
            <em>or</em>
            <%= link_to 'cancel', { :controller => :welcome } %>
          </small>
        </div>
      </section>
    </section>
  </div>

<% end %>